noxfile: re-mask Python 3.14
There is an issue with python-dispatch:

```
    from pydispatch.dispatch import *
  File "/var/lib/jenkins/workspace/gbp-feeds/.nox/tests-3-14/lib/python3.14/site-packages/pydispatch/dispatch.py", line 10, in <module>
    from pydispatch.aioutils import AioWeakMethodContainer, AioEventWaiters
  File "/var/lib/jenkins/workspace/gbp-feeds/.nox/tests-3-14/lib/python3.14/site-packages/pydispatch/aioutils.py", line 4, in <module>
    from _weakrefset import _IterationGuard
ImportError: cannot import name '_IterationGuard' from '_weakrefset' (/usr/lib/python3.14/_weakrefset.py)
```

This project is possibly no longer being maintained, which means we may
need to make adjustments.